---
title: Maracuja.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: OMGLOL
highlighter: true
exclude:
- Gemfile
- Gemfile.lock
- gems
